### PR TITLE
Allow URLs without any extension

### LINKED ISSUE #33: Crash when loading URLs without an extension
When loading URLs that don't end with an extension, I get [this error](https://github.com/johanhelsing/bevy_web_asset/blob/0cd80968ae0cbb601dbc54f6ce19826b96f28c03/src/web_asset_source.rs#L28):
```
asset paths must have extensions
```

I understand that we need to get the extension of the file to inject `.meta` to it to implement `read_meta`, but if there's no extension in the first place, I would say that it makes no sense to try to fetch the `meta` file.

Can we add support for URLs without extension? Maybe return a 404 error in `read_meta` in this case?

### PR DESCRIPTION
**Pull request by ThomasVille**
Fixes https://github.com/johanhelsing/bevy_web_asset/issues/33.

When `make_meta_uri` is called, if the URL ends with an extension, injects the `.meta` extension to it. If not, then return an error because we can't assume we can add an extension to a URL that didn't have one.

### CODE REVIEW

**Comment by johanhelsing** [comment]
Thanks

Hmmm.... What would be the downside of just always adding `.meta` instead, even if there is no extension?

**Comment by ThomasVille** [comment]
@johanhelsing I was thinking that if there's no extension in the original URL, then adding one doesn't make sense because the URL might end with something else than a file name.

For instance, if the glTF file is returned by a REST API like this:
```
https://example.com/api/gltf/8972016938af456cb3f8199e63a8673f016251/export
```
Then it doesn't make sense to send a query to:
```
https://example.com/api/gltf/8972016938af456cb3f8199e63a8673f016251/export.meta
```

This is basically the use-case I'm wanting to cover.

If you think we should send the query to `.meta` anyway then I can update my PR.

**Review by johanhelsing — APPROVED** [review]
I think it's ok like that. We can reevaluate later if someone has a use cause where we still would like to look for meta files.

**Comment by johanhelsing** [comment]
Thanks ❤️

**Pull request merged**
